| Tell what the daily Rambam learning should be.
| vim: ft=reva :


needs alg/enum
needs date/hebrew
with~ ~date

| enumerate the books of the yad:

0 enum: 
	INTRO MADA AHAVA ZMANIM NASHIM QEDUSHA HAFLAAH ZERAIM AVODAH QORBANOT
	TAHARAH NEZAQIN QINYAN MISHPATIM SHOFTIM #VOLUMES
enum;

0 enum: 
	| MADA:
	INTRO YESODEI-HATORAH DEOT TALMUD-TORAH AVODAH-ZARAH  TESHUVAH
	| AHAVA:
	QRIYAT-SHEMA TEFILLAH TEFILLIN TSITSIT BERACHOT MILAH SEDER-TEFILLAH
	| ZMANIM:
	SHABBAT EIRUVIN SHVITAT-ASOR SHVITAT-YOMTOV HAMETS-UMATSAH
	SHOFAR-SUKKAH-LULAV SHEQALIM QIDDUSH-HACHODESH TAANIYOT MEGILLA-VECHANUKAH
	| NASHIM:
	ISHUT GERUSHIN YIBUM-VECHALITSAH NAARAH-BETULAH SOTAH
	| QEDUSHA:
	ISSUREI-BIAH MAACHALOT-ASSUROT SHECHITAH
	| HAFLAAH:
	SHVUOT NEDARIM NEZIRUT ARACHIM-VECHARAIM
	| ZERAIM:
	KILAYIM MATNOT-ANIIM TERUMOT MAASEROT MAASER-SHENI BIKURIM SHEMITTA-VEYOVEL
	| AVODAH:
	BEIT-HABECHIRAH KLEI-HAMIQDAH BIAT-HAMIQDASH ISSUREI-MIZBEACH
	MAASEH-HAQORBANOT TEMIDIN-UMUSAFIN PESULEI-HAMUQDASHIN AVODAT-YOM-HAKIPPURIM
	MEILAH
	| QORBANOT:
	QORBAN-PESACH CHAGIGAH BECHOROT SHEGAGOT MECHUSAREI-KAPPARAH TEMURAH
	| TAHARAH:
	TUMAT-MET PARAH-ADUMAH TUMAT-TSARAAT METAMEI-MISHKAV-UMOSHAV
	SHEAR-AVOT-HATUMAOT TUMAT-OCHALIN KELIM MIQVAOT
	| NEZAQIN:
	NIZQEI-MAMON GENEIVA GEZEILA-VEAVEDAH CHOVEL-UMEZIQ ROTSEACH-USHEMIRAT-NEFESH
	| QINYAN:
	MECHIRAH ZECHIYAH-UMATANAH SHECHENIM SHELUCHIN-VESHUTAFIN AVADIM
	| MISHPATIM:
	SECHIRUT SHEELAH-UFIQADON MELAVEH-ULOVEH TOEN-VENITAN NACHALOT
	| SHOFTIM:
	SANHEDRIN EDUT MAMERIM EVEL MELACHIM-UMILCHAMOT
	#BOOKS
enum;

create booknames
	' INTRO , ' YESODEI-HATORAH , ' DEOT , ' TALMUD-TORAH , ' AVODAH-ZARAH ,  ' TESHUVAH ,
	' QRIYAT-SHEMA , ' TEFILLAH , ' TEFILLIN , ' TSITSIT , ' BERACHOT , ' MILAH ,
	' SEDER-TEFILLAH , ' SHABBAT , ' EIRUVIN , ' SHVITAT-ASOR , ' SHVITAT-YOMTOV ,
	' HAMETS-UMATSAH , ' SHOFAR-SUKKAH-LULAV , ' SHEQALIM , ' QIDDUSH-HACHODESH ,
	' TAANIYOT , ' MEGILLA-VECHANUKAH , ' ISHUT , ' GERUSHIN , ' YIBUM-VECHALITSAH ,
	' NAARAH-BETULAH , ' SOTAH , ' ISSUREI-BIAH , ' MAACHALOT-ASSUROT , ' SHECHITAH ,
	' SHVUOT , ' NEDARIM , ' NEZIRUT , ' ARACHIM-VECHARAIM , ' KILAYIM , ' MATNOT-ANIIM ,
	' TERUMOT , ' MAASEROT , ' MAASER-SHENI , ' BIKURIM , ' SHEMITTA-VEYOVEL ,
	' BEIT-HABECHIRAH , ' KLEI-HAMIQDAH , ' BIAT-HAMIQDASH , ' ISSUREI-MIZBEACH ,
	' MAASEH-HAQORBANOT , ' TEMIDIN-UMUSAFIN , ' PESULEI-HAMUQDASHIN ,
	' AVODAT-YOM-HAKIPPURIM , ' MEILAH , ' QORBAN-PESACH , ' CHAGIGAH , ' BECHOROT ,
	' SHEGAGOT , ' MECHUSAREI-KAPPARAH , ' TEMURAH , ' TUMAT-MET , ' PARAH-ADUMAH ,
	' TUMAT-TSARAAT , ' METAMEI-MISHKAV-UMOSHAV , ' SHEAR-AVOT-HATUMAOT ,
	' TUMAT-OCHALIN , ' KELIM , ' MIQVAOT , ' NIZQEI-MAMON , ' GENEIVA , ' GEZEILA-VEAVEDAH ,
	' CHOVEL-UMEZIQ , ' ROTSEACH-USHEMIRAT-NEFESH , ' MECHIRAH , ' ZECHIYAH-UMATANAH ,
	' SHECHENIM , ' SHELUCHIN-VESHUTAFIN , ' AVADIM , ' SECHIRUT , ' SHEELAH-UFIQADON ,
	' MELAVEH-ULOVEH , ' TOEN-VENITAN , ' NACHALOT , ' SANHEDRIN , ' EDUT , ' MAMERIM , ' EVEL ,
	' MELACHIM-UMILCHAMOT ,

create chapters
	12 , |	INTRO 
	| MADA
		10 , | YESODEI-HATORAH 
		7  , | DEOT 
		7  , | TALMUD-TORAH 
		12 , | AVODAH-ZARAH 
		10 , | TESHUVAH
	| AHAVAH
		4  , | QRIYAT-SHEMA 
		15 , | TEFILLAH 
		10 , | TEFILLIN 
		3  , | TSITSIT 
		11 , | BERACHOT 
		3  , | MILAH 
		3  , | SEDER-TEFILLAH ?
	| ZMANIM
		30 , | SHABBAT 
		8  , | EIRUVIN 
		3  , | SHVITAT-ASOR 
		8  , | SHVITAT-YOMTOV 
		9  , | HAMETS-UMATSAH ( + hagadah )
		8  , | SHOFAR-SUKKAH-LULAV 
		4  , | SHEQALIM 
		19 , | QIDDUSH-HACHODESH 
		5  , | TAANIYOT 
		4  , | MEGILLA-VECHANUKAH
	| NASHIM
		25 , | ISHUT 
		13 , | GERUSHIN 
		8  , | YIBUM-VECHALITSAH 
		3  , | NAARAH-BETULAH 
		4  , | SOTAH
	| QEDUSHA
		22 , | ISSUREI-BIAH 
		17 , | MAACHALOT-ASSUROT 
		14 , | SHECHITAH
	| HAFLAAH
		12 , | SHVUOT 
		13 , | NEDARIM 
		10 , | NEZIRUT 
		8  , | ARACHIM-VECHARAIM
	| ZERAIM:
		10 , | KILAYIM 
		10 , | MATNOT-ANIIM 
		15 , | TERUMOT 
		14 , | MAASEROT 
		11 , | MAASER-SHENI 
		12 , | BIKURIM 
		13 , | SHEMITTA-VEYOVEL
	| AVODAH:
		8  , | BEIT-HABECHIRAH 
		10 , | KLEI-HAMIQDAH 
		9  , | BIAT-HAMIQDASH 
		7  , | ISSUREI-MIZBEACH
		19 , | MAASEH-HAQORBANOT 
		10 , | TEMIDIN-UMUSAFIN 
		19 , | PESULEI-HAMUQDASHIN 
		5  , | AVODAT-YOM-HAKIPPURIM
		8  , | MEILAH
	| QORBANOT:
		10 , | QORBAN-PESACH 
		3  , | CHAGIGAH 
		8  , | BECHOROT 
		15 , | SHEGAGOT 
		5  , | MECHUSAREI-KAPPARAH 
		4  , | TEMURAH
	| TAHARAH:
		25 , | TUMAT-MET 
		15 , | PARAH-ADUMAH 
		16 , | TUMAT-TSARAAT 
		13 , | METAMEI-MISHKAV-UMOSHAV
		20 , | SHEAR-AVOT-HATUMAOT 
		16 , | TUMAT-OCHALIN 
		28 , | KELIM 
		11 , | MIQVAOT
	| NEZAQIN:
		14 , | NIZQEI-MAMON 
		9  , | GENEIVA 
		18 , | GEZEILA-VEAVEDAH 
		8  , | CHOVEL-UMEZIQ 
		13 , | ROTSEACH-USHEMIRAT-NEFESH
	| QINYAN:
		30 , | MECHIRAH 
		12 , | ZECHIYAH-UMATANAH 
		14 , | SHECHENIM 
		10 , | SHELUCHIN-VESHUTAFIN 
		9  , | AVADIM
	| MISHPATIM:
		13 , | SECHIRUT 
		8  , | SHEELAH-UFIQADON 
		27 , | MELAVEH-ULOVEH 
		16 , | TOEN-VENITAN 
		11 , | NACHALOT
	| SHOFTIM:
		26 , | SANHEDRIN 
		22 , | EDUT 
		7  , | MAMERIM 
		14 , | EVEL 
		12 , MELACHIM-UMILCHAMOT

: count temp off chapters #BOOKS 0do 
	lcount temp +!
	loop drop temp @ ;

count constant #CHAPTERS
| starting point: 13 AV 5766
5 14 5766 hebrew>fixed constant START-CYCLE

: hagadah temp off HAMETS-UMATSAH 1+ 1+ 0do chapters i cells + @ temp +! loop temp @ 1- ;
hagadah constant HAGADAH
: intro?  ( n -- )
	dup 0 chapters @ between if
		| n
		." Intro " .
		rdrop
	then
	;

variable 3?
: .perek ( n -- )
	dup .
	intro?
	dup HAGADAH = if
		drop ." HAGADAH"
	;then
	#CHAPTERS 0do
		| n
		i cells chapters + @
		2dup
		| n chapters n chapters
		<if 
			drop 1+ i cells booknames + @ xt>name type space . leave
		then
		-
	loop
	;
: 3perek ( n -- ) 3? on 1- 3 * 1+ dup 3 + swap do i .perek space loop ;
: 1perek ( n -- ) 3? off .perek ;
: perek ( n -- )
	." One perek: " 1perek cr
	." Three perakim: " 3perek cr
	;
: shiur ( fdate -- )
	dup
	dup fixed>gregorian .date space 
	'( emit fixed>hebrew .hebrew ') emit space
	START-CYCLE -  | n  -- number of days since start of cycle
	#CHAPTERS mod  | rem -- number of chapters...
	dup perek ;
: today? today>fixed shiur ;
: date? gregorian>fixed shiur ;
: hdate? hebrew>fixed shiur ;
